version: '3.9'

services:
  django:
    image: docker-django-v0.0 
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: 'on-failure'

  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine 
    expose:
      - 6379 